### ISSUE TITLE
TODO (spritework)

### ISSUE THREAD

**Issue by TowerofCone** [AlphaPassive/SS13-mlp-Station#1]
You know when i said i would save you incompetent rambling?
I lied.
TODO:
~~+Patch in ponybot spritesheet for Silicons that i managed to save from whatever bad sector hell my HDD is suffering from- need animations for module changes and to remap some modules~~ Done, barring Higgs-Bugson and one unsprited base model.
+Remake PONDAN sprites for AI core. Then add them.
~~+Caffeine.~~ I have plenty now.
+Maybe actually play the fucking game instead of getting trapped in code and sprite hell again.
~~-Remove coderbus stupidity once i find it under all of my own.~~ Can't do it, chief.

+Make Pony sprites for Carbons.
+Actually have those correspond to races again.
+Playable ponies (the code was never meant to handle this much autism).
~Probably everything else i'm not thinking of right now. Please help. I'm retarded.

**Comment by AlphaPassive** [comment]
I sent you an Invite to edit the files, I would love your help.. I got no knowledge of code and I only thing I could do is add sprites but I can't create shit.

**Comment by TowerofCone** [comment]
BYOND is definitely not the way to (re)cut your teeth. Sleep first, hell after.

**Comment by AlphaPassive** [comment]
Sounds good, get your rest... hopefully more people will be willing to contribute to this tommorow

**Comment by AlphaPassive** [comment]
![Action Spam](https://user-images.githubusercontent.com/58754146/125532381-b4b52595-43c5-40f0-be79-55bbde914f9d.PNG)
You know how to fix this? my inbox went nuts!

**Comment by TowerofCone** [comment]
what in the goddamn?

**Comment by AlphaPassive** [comment]
Mind looking into it? it's on the Actions tab

**Comment by TowerofCone** [comment]
Manually disabled for the moment. I'm sure it's important in some way and will fuck us raw later, but for now...

**Comment by AlphaPassive** [comment]
![image](https://user-images.githubusercontent.com/58754146/125533646-45cd4616-3bdb-4536-b75e-e635790b8c9d.png)
Thanks, I noticed on the /tg/ github they've got it up.. but keep focusing on what you want to work on I don't want to burden you with this for now.

**Comment by AlphaPassive** [comment]
Hey what's your PC specs? I just did a bit of digging and apparently to run a server you need around 4GBram and 2core cpu.. I've got way more than that but I have shit internet as an Ausfag.. if you match the specs you could run the server

**Comment by TowerofCone** [comment]
My net is genuinely worse than ausnet.

**Comment by AlphaPassive** [comment]
Alright, I'm looking into Virtual Servers.. looking at all these sites is giving me a headache... I've also asked around /vg/ and /tg/ on how they hose their servers since I can't find any info anywhereere

**Comment by TowerofCone** [comment]
No point in rushing it. Don't hurt yourself.

**Comment by AlphaPassive** [comment]
All good I got work in 4 hours anyway so I want to at least make some progress, make sure to bump the thread when I'm gone.

**Comment by AlphaPassive** [comment]
Alright I got heaps of free time now, The sprite you shared on the thread is looking good.. I'll start work on hosting the server again soon.. just need to rest a bit.

**Comment by TowerofCone** [comment]
Once i have one sheet going it's not terribly hard to replicate for others. The back sprite's scuffed but there's really only one alternative and that's the side-back that the Ponk sprites have. Once i figure out how to make the damn git client PR the repo here we'll have ponebots, and it's only up from there.

**Comment by AlphaPassive** [comment]
Ok server is up, let me know when you're done with your robopones I'll add them to the server unless it automatically updates from the Github? anywho I'll send you the IP once you're ready.

**Comment by AlphaPassive** [comment]
Also if you can find a way to change the shift + right click Examine back to Right Click that would be great.. I really don't like that change.

**Comment by TowerofCone** [comment]
It'd probably require ferreting out the commit that did so.

**Comment by AlphaPassive** [comment]
Alright, I'm going to release the server to the Thread now.

**Comment by TowerofCone** [comment]
Sorry about that, i passed out. Final pass to make sure there's no fuckery (ex: Service light overriding Pony light for that model, which is bad) and then i'll merge.
TwAI isn't playing nice with the picker for some reason, but c'est la vie. I'll figure it out later, i need a break from BYOND.

**Comment by AlphaPassive** [comment]
We're moving to /vg/ Code.

**Comment by TowerofCone** [comment]
I've been watching the thread. Closing this until rebasing is complete.
